(in-package :lisputils-tests)


(defsuite* lisputils-tests)

(deftest plist-utils-tests ()
  (is (equal (plist-collect '() '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '()))
  (is (equal (plist-collect '(:a :c) '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(:a 1 :c 3)))
  (is (equal (plist-collect '(:a :b :c) '())
             '()))
  (is (equal (plist-collect-if (lambda (i)
                                 (member i (list :a :b)))
                               '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(:a 1 :b 2)))
  (is (equal (plist-collect-if #'evenp
                               '(:a 1 :b 2 :c 3 :d 4 :e 5) :on-values-p t)
             '(:b 2 :d 4)))
  (is (equal (plist-collect-if #'stringp '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '()))
  (is (equal (plist-keys '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(:A :B :C :D :E)))
  (is (equal (plist-vals '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(1 2 3 4 5)))
  (is (equal (plist-map-vals (lambda (x) (* 10 x)) '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(:A 10 :B 20 :C 30 :D 40 :E 50)))
  (is (equal (plist-map (lambda (key val)
                          (with-output-to-string (str)
                            (princ key str)
                            (princ #\- str)
                            (princ val str)))
                        '(:a 1 :b 2 :c 3 :d 4 :e 5))
             '(:A "A-1" :B "B-2" :C "C-3" :D "D-4" :E "E-5"))))
